[build]
builder = "nixpacks"
buildCommand = "npm ci --omit=dev"

[deploy]
startCommand = "npm run railway:start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[ports]]
port = "3001"
protocol = "tcp"

[service]
internal_port = "3001"